#Test için düzenlenmiştir


version: '3.8'

services:
  db:
    image: postgres:13.8
    restart: always
    environment:
      POSTGRES_DB: wa_db  # Kullanılacak veritabanı adı
      POSTGRES_USER: postgres  # db.env ile aynı olmalı
      POSTGRES_PASSWORD: mysecretpassword  # db.env ile aynı
      POSTGRES_HOST_AUTH_METHOD: trust  # ← bu satırı EKLE
    ports:
      - "55432:5432"  # Hostta 55432, container içinde 5432
    volumes:
      - postgresData:/var/lib/postgresql/data  # Kalıcı veritabanı depolaması
    network_mode: bridge
    cap_drop:
      - MKNOD

  wacore:
    image: docker.whatsapp.biz/coreapp:v${WA_API_VERSION}
    command:
      - "/opt/whatsapp/bin/wait_on_postgres.sh"
      - "/opt/whatsapp/bin/launch_within_docker.sh"
    volumes:
      - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - db
    network_mode: bridge
    cap_drop:
      - MKNOD

  waweb:
    image: docker.whatsapp.biz/web:v${WA_API_VERSION}
    command:
      - "/opt/whatsapp/bin/wait_on_postgres.sh"
      - "/opt/whatsapp/bin/launch_within_docker.sh"
    ports:
      - "9090:443"  # HTTPS dış bağlantı portu
    volumes:
      - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WACORE_HOSTNAME: wacore
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - db
      - wacore
    network_mode: bridge
    cap_drop:
      - MKNOD

volumes:
  postgresData:
  whatsappMedia:

